import "./globals.css";

export const metadata = {
  title: "Tomoru - Japanese Restaurant",
  description: "Generated by create next app",
};

import { Footer } from "@/components/Footer";
import { Theme } from "@/components/Theme";

import { cookies } from "next/headers";

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get('theme');
  let theme = '';

  if (!themeCookie) {
    theme = 'light'; 
  } else {
    theme = themeCookie.value;
  }

  return (
    <html lang='en' className={theme}>
      <body className='bg-seasalt text-eerie-black dark:bg-black dark:text-seasalt'>
          <Theme></Theme>
          {children}
          <Footer></Footer>
      </body>
    </html>
  );
}
