import "./globals.css";

export const metadata = {
  title: "Tomoru - Japanese Restaurant",
  description: "Generated by create next app",
};

import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { Theme } from "@/components/Theme";

import { cookies } from "next/headers";

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();

  const theme = cookieStore.get('theme').value || 'light';

  return (
    <html lang='en' className={theme}>
      <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyALrIVg4b_3xwpUq4qD2uxk7ciTYp5-2Jg&callback=initMap" async defer loading='async'></script>
      <body className='bg-seasalt text-eerie-black dark:bg-black dark:text-seasalt'>
          <Header></Header>
          <Theme></Theme>
          {children}
          <Footer></Footer>
      </body>
    </html>
  );
}
